### ISSUE TITLE
Botón sin acción en el checkout

### ISSUE THREAD

**Issue by cristinamartinrod** [ctmil/payment_mercadopago#10]
Tras la instalación e incluir los credenciales muestra el botón en el checkout, pero sin ninguna acción. Hay que hacer alguna modificación?

Muchas gracias por tu ayuda!

**Comment by hriveros** [comment]
Ejecuta paypal antes luego le das cancelar y te funcionara. Al menos a mi me funciono, de lo contrario no te redirecciona y mas aun ningun otro medio de pago queda funcionando, debes salir de la sesion y entrar nuevamente desde ahi los otros medios de pago funcionan y si iniciaste primero paypal, mercadopago tambien funciona el porque ni idea. Vi el codigo pero es bastante complejo y se ve que no sigue al pie la nueva API

**Comment by pleirb** [comment]
A mi me pasa exactamente lo mismo, lo curioso es que en un principio funciono bien cuando recian lo habia instalado y luego de instalarlo en otra copia de odoo (producción) dejo de funcionar el boton como dice cristinamartinrod en las dos instalaciones de odoo. Esto que dices (hriveros) es como para probar o repara definitivamente, hay que incluir crear un modo de pago paypal? es esto?

**Comment by pleirb** [comment]
Dejo aquí el LOG que arroja:

2018-10-01 20:43:54,018 1272 ERROR web.hfnet.uy odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/website_sale/controllers/main.py", line 852, in payment_transaction
    'billing_partner_id': order.partner_invoice_id.id,
  File "/odoo/odoo-server/addons/payment/models/payment_acquirer.py", line 305, in render
    values = method(values)
  File "/odoo/custom/addons/payment_mercadopago/models/mercadopago.py", line 180, in mercadopago_form_generate_values
    print "sorder_s.order_line[0]: ", sorder_s.order_line[0].name
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 66: ordinal not in range(128)
2018-10-01 20:43:54,156 1272 INFO web.hfnet.uy werkzeug: 192.168.1.106 - - [01/Oct/2018 20:43:54] "POST /shop/payment/transaction/11 HTTP/1.1" 200 -

**Comment by pleirb** [comment]
Dejo aquí el LOG que arroja:

2018-10-01 20:43:54,018 1272 ERROR servidorodoo odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/website_sale/controllers/main.py", line 852, in payment_transaction
    'billing_partner_id': order.partner_invoice_id.id,
  File "/odoo/odoo-server/addons/payment/models/payment_acquirer.py", line 305, in render
    values = method(values)
  File "/odoo/custom/addons/payment_mercadopago/models/mercadopago.py", line 180, in mercadopago_form_generate_values
    print "sorder_s.order_line[0]: ", sorder_s.order_line[0].name
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 66: ordinal not in range(128)
2018-10-01 20:43:54,156 1272 INFO servidorodoo werkzeug: 192.168.1.106 - - [01/Oct/2018 20:43:54] "POST /shop/payment/transaction/11 HTTP/1.1" 200 -

**Comment by pleirb** [comment]
Bueno, encontré cual es el problema. Al parecer es por los caracteres extraños que se pueden encontrar en sorder_s.order_line[0].name. Puntualmente en mi caso el error es: UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 66: ordinal not in range(128)
Quiere decir que en la posición 66 del string hay un carácter (en este caso un acento) que no se puede codificar y lo que sucede en la web es absolutamente nada, no hay captura de este error.
Así que he quitado acentos tanto en los nombres de los productos como en las descripciones y todo funciona de maravillas. Me gustaría saber si hay alguna forma de corregir ir el código para poder usar acentos y otros caracteres sin experimentar este problema. Ideas?

**Comment by morrillo** [comment]
lo primero que podemos hacer es eliminar la linea del print. Luego lo hacemos

**Comment by pleirb** [comment]
Creo que ya hice eso sin suerte, lo voy a intentar otra ves porque creo que había comentado la linea. Hay que recargar el modulo o actualizarlo desde el administrador de aplicaciones para tenga efecto?
El print de esa linea donde imprime esa info? Es para el LOG?

**Comment by morrillo** [comment]
De vuelta... esto es para los issues y problemas del módulo. No para comentar su uso. Si no sabes como actualizar un módulo en odoo, no es el lugar para pedir información. Hay otros foros (por ejemplo odoo-argentina) donde podes preguntar eso
