### ISSUE TITLE
Notificaciones ERROR en log de odoo

### ISSUE THREAD

**Issue by guzzi235** [ctmil/payment_mercadopago#2]
Al hacer la prueba de notificaciones en ipn de mercadopago tira este error:

Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/addons/base/ir/ir_http.py", line 154, in _dispatch
    rule, arguments = self._find_handler(return_rule=True)
  File "/opt/odoo/openerp/addons/base/ir/ir_http.py", line 65, in _find_handler
    return self.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1433, in match
    raise NotFound()
NotFound: 404: Not Found

**Comment by danimaribeiro** [comment]
Do you have more than one database?
If yes, you should configure dbfilter param.

**Comment by guzzi235** [comment]
Hola no solo tengo una base de datos.

**Comment by csrocha** [comment]
El IPN no funcionaba en la versión anterior. Ahora si.
